name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

<<<<<<< HEAD
      - name: Install
=======
      - name: Install dependencies
>>>>>>> 96cfa0d35c7e0ac81573dfc435df0ce366a20f74
        run: npm install

      - name: Build
        run: npm run build

<<<<<<< HEAD
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
=======
      - name: Verify dist
        run: |
          echo "=== DIST ==="
          ls -R dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
>>>>>>> 96cfa0d35c7e0ac81573dfc435df0ce366a20f74
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
<<<<<<< HEAD
=======
    needs: build
    runs-on: ubuntu-latest

>>>>>>> 96cfa0d35c7e0ac81573dfc435df0ce366a20f74
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

<<<<<<< HEAD
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
=======
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
>>>>>>> 96cfa0d35c7e0ac81573dfc435df0ce366a20f74
